name = "SeisProcessing"
uuid = "3ac90d68-5a11-50c7-932e-af3f40d97fdc"
authors = ["fercarozzi <carozzi@ualberta.ca>"]
version = "0.1.0"

[deps]
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SeisPlot = "00783350-183d-11e9-0ed7-9f3f45823183"
